let challenge = '30 Days Of JavaScript'
console.log(challenge)
console.log(challenge.length)
console.log(challenge.toUpperCase())
console.log(challenge.toLowerCase())
console.log(challenge.substr(0,2))
console.log(challenge.substring(0,2))
console.log(challenge.substring(3))
console.log(challenge.includes('Script'))
console.log(challenge.split())
console.log(challenge.split(' '))
console.log(('Facebook, Google, Microsoft, Apple, IBM, Oracle, Amazon').split(', '))
console.log(challenge.replace('JavaScript', 'Python'))
console.log(challenge.charAt(15))
console.log(challenge.charCodeAt(11))
console.log(challenge.indexOf('a'))
console.log(challenge.lastIndexOf('a'))
let phrase = 'You cannot end a sentence with because because because is a conjunction'
console.log(phrase.indexOf('because'))
console.log(phrase.lastIndexOf('because'))
console.log('You cannot end a sentence with because because because is a conjunction'.search('because'))
console.log(' 30 Days Of JavaScript '.trim())
console.log(challenge.startsWith('30'))
console.log(challenge.endsWith('Script'))
let pattern = /a/g
console.log(challenge.match(pattern))
let day = '30 Days Of ', js = 'JavaScript'
console.log(day.concat(js))
console.log(challenge.repeat(2))